Hotfix/752 watchdog notification
4forges/karmap pull request #7
Opened 2019-06-04 08:46 UTC by meox

2019-06-04 11:42 UTC, meox commented
I decided to use the HTTP Api because (for what I can see from code and documentation) is not possible to have a secondary Airbrake notifier.

This is important because we want to log Karma::Watchdog activities (:startup, :stop) on a dedicated Airbrake project and because this GEM is included as dependency inside PulsarPlatform we cannot override the default initializer.

2019-06-04 11:46 UTC, meox commented
already on staging

2019-06-04 11:47 UTC, meox commented
Issue: https://github.com/pulsarplatform/pulsarplatform/issues/752

2019-06-05 11:37 UTC, abrazzini requested changes

2019-06-05 11:37 UTC, abrazzini commented on lib/karmap/watchdog.rb
> +    def send_airbrake_notification(notification_type = 'notification')
sync parameters with documentation
the method seems to require notification param
check also the call (raw: 118)

2019-06-05 11:37 UTC, abrazzini commented on lib/karmap/watchdog.rb
> +      send_airbrake_notification('stop')
check the params

2019-06-05 11:37 UTC, abrazzini commented on lib/karmap/watchdog.rb
> +      send_airbrake_notification('startup')
check the param

2019-06-05 16:37 UTC, merged